### ISSUE TITLE
WTF# is Live Coding?, with Gareth Hubball

### ISSUE THREAD

**Issue by StachuDotNet** [wtfsharp/episodes#1]
Hi there @garethhubball!

As I mentioned, I'm pulling my brain back into WTF# mode and thought that GitHub would be a better place to organize, rather than aimlessly working through twitter DMs :)
If you don't mind, I'd like to continue our planning here.

At the end of our last discussion, we decided to cover the topic of code live streaming; the ecosystem around it, your journey and inspiration, your experience, etc.

I'll follow up on this more later - this is a placeholder for now.

If you could do me one favor:
Think of a title in the form of "WTF# is ___". Maybe something like "WTF# is Code Live Streaming"? I feel like there's a better title out there...

**Comment by garethhubball** [comment]
Would something like `WTF# is Getting Started?` or `WTF# are Resources?` work?

**Comment by garethhubball** [comment]
@StachuDotNet - Did you get any feedback from Jeff on this one?

**Comment by StachuDotNet** [comment]
Hmm - those titles don't quite match what I was hoping to discuss.
I was hoping to discuss the world of live-streaming teaching and coding, coming specifically from the angle of twitch/youtube, the the dev-communities that exist there, as it's a foreign topic to me.
I'd love to go through how you structure your lessons/sessions towards a beginner-friendly audience, but "getting started with F#" isn't quite a topic I had in mind just yet.

Jeff seems to be quite busy these days, so I'll refrain from bugging him for now. :)

**Comment by garethhubball** [comment]
I’m with you on not bugging Jeff. Would you go for something like WTF# is
Twitch Streaming or WTF# is streaming code?
-- 
Gareth Lees BSc.(Hons)

**Comment by garethhubball** [comment]
Maybe WTF# is Live coding on Twitch? Thinking stream could confuse people
who know about MemoryStreams and the like?
-- 
Gareth Lees BSc.(Hons)

**Comment by StachuDotNet** [comment]
One more draft: "WTF# is Live Coding?" 
That way we don't limit discussion purely to Twitch (YouTube has some live streaming capabilities as well, but certainly we'll mention that Twitch is dominating the market).

What's does your schedule look like on Sunday, November 18th? Do you have a 90min time-slot to record? 
If so, I'll make sure I get an initial outline to you by EOD Monday. (which I'd kindly request you to review/adjust for ~30mins prior to recording).
If not, no worries - we can do 24th/25th if that's better for you.

**Comment by StachuDotNet** [comment]
Cool - how does 230p-4p UTC on the 18th sound? (930a-11a EST)
I'll get an outline to you tomorrow night.

**Comment by garethhubball** [comment]
That sounds perfect to me thank you – hopefully we get a good enough sound from my microphones. Just to let you know: The beginner’s series is ending next week and turning more into a “deep dives” series where we look into things with more depth than normal and while it’s still suitable for beginners it’s moving from a “teaching” format to a “discovery” format.

Sent from Mail for Windows 10

**Comment by StachuDotNet** [comment]
Fantastic. The above-mentioned timeslot is now scheduled in my calendar.
I'll link the outline here by EOD tomorrow - cheers.

Will be good talking about that transition then.

**Comment by StachuDotNet** [comment]
Tuesday is just the second Monday of the week, right? :)
Here is a link to a rough outline: https://dynalist.io/d/wiJHChpgRzVpQwfKaGkKr4Wi

The above link is view-only, as I wouldn't want random people coming into our document and modifying it. As such, I'll find your email and make sure you're able to edit with me.

Cheers!

**Comment by StachuDotNet** [comment]
@fergusmeiklejohn in your hands now :)

**Comment by StachuDotNet** [comment]
Episode been out; thanks to @garethhubball and @fergusmeiklejohn. Closing.
