### ISSUE TITLE
WTF# is CQRS and Event Sourcing?, with Roman Sachse

### ISSUE THREAD

**Issue by StachuDotNet** [wtfsharp/episodes#11]
Hi there @rommsen. Fergus mentioned that you _might_ be interested in recording a WTF# episode on these topics. Any interest? :)

**Comment by rommsen** [comment]
Yes. Of course. Would be honored

**Comment by StachuDotNet** [comment]
Great! What's your schedule look like?
In total, an episode takes about a 4-5hr commitment for a guest, depending on topic.
Please see the root readme.md for what to expect.

Cheers!

**Comment by rommsen** [comment]
My schedule is pretty packed until the beginning of december. I am also in the planning of an "Event Sourcing - Do it yourself" series for my Dev-Owl Youtube channel which should be released for the F# advent calender on the 23rd of December. I would love to combine this a bit with the podcast if possible. My ideal schedule for this would be: 
* Prediscussion about topics between December 1st and 15th
* Recording between December 27th and January 6th.

What do you think about this schedule? Do you see any problems with this?

**Comment by rommsen** [comment]
Hey @StachuDotNet what do you think about the schedule? Is it too late for you? Any problems?

**Comment by StachuDotNet** [comment]
Schedule sounds good to me.
Please let me know your availability and timezone for Dec 1-2 (15min call), and Dec 29-30 (90min call).
I am currently open those days.

**Comment by rommsen** [comment]
@StachuDotNet: My timezone is UTC+01:00. I am available on the 1st and 29th of december between 4pm and 9pm local time and on the 2nd and 30th of december between 10am and 9pm local time.

**Comment by StachuDotNet** [comment]
Thank you @rommsen for coordinating with me.

I've added these appointments to my calendar for our initial chat and actual recording:
- Initial chat: (7pm UTC+1) = (1pm EST) on December 1st, for 15 minutes.
- Recording: (7pm UTC+1) = (1pm EST) on December 29th, for 90 minutes. 

Figured I'd stick with the same start time to keep things simple :)

For the first call, is Google HangOuts OK with you? My account is hello@stachu.net - please ping me in chat in the meantime to make sure we can connect that way.

Please let me know if any of the above doesn't work for you.

I'm looking forward to speaking with you about these subjects! My favorite talk *ever* is Greg Young's talk about event sourcing at an old Code on the Beach conference - I've watched it at least 3 times, and it inspired me to write a hand-rolled client-side event-sourced application.. in javascript! Anyway, I'm sure we'll have lots to talk about, and I'm looking forward to recording and releasing it.

**Comment by StachuDotNet** [comment]
@rommsen A few tomorrow's later, I have a general outline here:
https://dynalist.io/d/TMwsGOviaFYgtTgU8HFlmmUh

I'll be following up privately with a link that will allow you to edit the document as you wish.

I'll take a look at this once or twice before our recording; other than that, I look forward to recording with you on the 29th - please let me know if you have any questions, concerns, or recording date change requests.

**Comment by StachuDotNet** [comment]
Hi there @rommsen. Hope you're having a merry Christmas, if you celebrate.

I'll need to postpone our recording by several days due to a family emergency. Will follow up later.

**Comment by rommsen** [comment]
Hey Stachu.

I can totally understand. Family first. Always. All the best for you.

Roman

Stachu Korick <notifications@github.com> schrieb am Di., 25. Dez. 2018,
13:14:
