### ISSUE TITLE
Episode: Elmish, with Alfonso and Kunjan

### ISSUE THREAD

**Issue by StachuDotNet** [wtfsharp/episodes#2]
Next step: re-record intro and get all recordings to @fergusmeiklejohn

**Comment by fergusmeiklejohn** [comment]
I have time to edit it this week

**Comment by StachuDotNet** [comment]
@fergusmeiklejohn in your hands now :)

cc @alfonsogarciacaro, @kunjee17 - finally re-recorded the intro as promised.

**Comment by StachuDotNet** [comment]
And it's out <3
Thanks again to relevant parties ^^. See you in another episode later. :)
